### ISSUE TITLE
Arrow keys and return key shortcuts not being processed by autocomplete

### ISSUE THREAD

**Issue by cwhite-connectfirst** [contentco/quill-emoji#45]
In the demo, I'm unable to either focus on different emojis via the arrow keys or select the emoji I want via the enter key. I think this is happening because of the format field that's being applied to the keybindings for arrow keys (see https://github.com/contentco/quill-emoji/blob/master/src/module-emoji.js#L58 and https://github.com/contentco/quill-emoji/blob/master/src/module-emoji.js#L64). If I remove those lines, I'm able to focus on different emojis again.

Normally, I'd submit a PR for removing those lines, but after looking into the `triggerPicker` method a bit, it seems like there was an attempt to limit the scope of those keybindings to text that was added to quill with a specific format indicating that the picker was open. Do you guys want to try to get the keybindings for the `emoji-shortname` format working, or would it be alright if I removed the format constraint on the arrow key bindings and removed the insert of the `emoji-shortname` formatted text from `triggerPicker`?

**Comment by cwhite-connectfirst** [comment]
@himynameistimli @yeminhtut Any thoughts?

**Comment by himynameistimli** [comment]
Sorry @cwhite-connectfirst 	for the delay, I haven't had a chance to really dig into this, and it's been a while since we've used this in our own editor.

If this is what I think we're talking about, then the original goal was to emulate typical editors in how they use the `:` key to trigger the selector. If you're telling me it's not working then I guess theres no point in trying to preserve the code, though likely I would like to fix this broken behavior.

I think it should be ok to add your PR, but I would like to loop in @klaslundberg  too in case there are any other issues.

**Comment by cwhite-connectfirst** [comment]
Cool, thanks for getting back to me. I'll submit a PR in the next week or so.

**Comment by cwhite-connectfirst** [comment]
https://github.com/contentco/quill-emoji/pull/55
